version: '3.8'

services:
  mysql-db:
    build: ./padelManager-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: padelmanager
    networks:
      - my_network

  backend:
    build: 
      context: ./padelManager-backend  
      dockerfile: Dockerfile
    environment:
      - MYSQL_URL=jdbc:mysql://mysql-db:3306/padelmanager
      - RUTA_ANGULAR=http://prodiasv19.fis.usal.es:4200
    depends_on:
      - mysql-db
    networks:
      - my_network

  frontend:
    build: ./padelManager-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
      - mysql-db
    networks:
      - my_network

networks:
  my_network:
    driver: bridge
